#ifndef FASTBOOT_MENU
#define FASTBOOT_MENU

enum action {
	ACTION_START,
	ACTION_REBOOT_RECOVERY,
	ACTION_REBOOT_BOOTLOADER,
	ACTION_REBOOT_FASTBOOTD,
	ACTION_REBOOT_DOWNLOAD,
	ACTION_POWEROFF = 5,
	ACTION_END,
};

int fastboot_menu_entry(void*);

#endif /* FASTBOOT_MENU */
